name:                mal-backend
version:             0.1.0.0
github:              "baffalop/mal-backend"
license:             BSD3
author:              "Nikita Gaidakov"
maintainer:          "nikita.gaidakov@gmail.com"
copyright:           "2021 Nikita Gaidakov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/baffalop/mal-backend#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- microlens
- wai
- warp
- http-types
- websockets
- wai-websockets
- wai-app-static
- aeson

library:
  source-dirs: src

executables:
  mal-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - mal-backend

tests:
  mal-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mal-backend
